version: '3'

services:
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
